/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/datav/RightChart1 copy 2.vue')['default']
    BootomChart: typeof import('./src/components/datav2/BootomChart.vue')['default']
    BottomChart1: typeof import('./src/components/datav/BottomChart1.vue')['default']
    BottomChart2: typeof import('./src/components/datav/BottomChart2.vue')['default']
    BottomCharts: typeof import('./src/components/datav/BottomCharts.vue')['default']
    Cards: typeof import('./src/components/datav2/cards.vue')['default']
    CenterCmp: typeof import('./src/components/datav/CenterCmp.vue')['default']
    copy: typeof import('./src/components/datav copy/index.vue')['default']
    Datav: typeof import('./src/components/datav/index.vue')['default']
    Datav2: typeof import('./src/components/datav2/index.vue')['default']
    DigitalFlop: typeof import('./src/components/datav2/digitalFlop.vue')['default']
    LabelTag: typeof import('./src/components/datav/LabelTag.vue')['default']
    LeftChart1: typeof import('./src/components/datav/LeftChart1.vue')['default']
    LeftChart2: typeof import('./src/components/datav/LeftChart2.vue')['default']
    LeftChart3: typeof import('./src/components/datav/LeftChart3.vue')['default']
    RankingBoard: typeof import('./src/components/datav2/rankingBoard.vue')['default']
    RightChart1: typeof import('./src/components/datav/RightChart1.vue')['default']
    RightChart2: typeof import('./src/components/datav/RightChart2.vue')['default']
    RoseChart: typeof import('./src/components/datav2/roseChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBoard: typeof import('./src/components/datav2/scrollBoard.vue')['default']
    TopHeader: typeof import('./src/components/datav2/topHeader.vue')['default']
    TopHeader1: typeof import('./src/components/datav/topHeader1.vue')['default']
    WaterLevelChart: typeof import('./src/components/datav2/waterLevelChart.vue')['default']
  }
}
